### PR TITLE
fixed the issues

### PR DESCRIPTION
**Pull request by devopstrainers1**
Hi,

Please review my changes and approve it.
It's test on QA env, this will fix bug 190909

### CODE REVIEW

**Comment by DanyLan** [comment]
approve

**Comment by yogeshdarekar** [comment]
Approved

**Review by ManviSood — APPROVED** [review]
Approved

**Review by yogeshdarekar — APPROVED** [review]
Approved, Not working on Edge browser.Works on Other. Thanks

**Pull request merged**
